#!/bin/bash

[[ -f ./chemistry.config.json.xml ]] || node ./chemistry.config.js

[[ -f ./collection.assembled.xml ]] || xmllint --pretty 1 ../data/chemistry-2e/collection.assembled.xhtml > ./collection.assembled.xml

saxon -xsl:./ident.xsl -s:./chemistry.config.json.xml -o:./chemistry.config.xml
saxon -xsl:./compile-xslt.xsl -s:./chemistry.config.xml -o:./autogenerated.xsl

saxon -xsl:./transform.xsl -s:./collection.assembled.xml -o:./output-transform.xml

saxon -xsl:./autogenerated.xsl -s:./collection.assembled.xml -o:./output-autogenerated.xml
