#!/bin/bash

die() {
  echo
  echo "*** $@" >&2
  exit 1
}

XSLT_COVERAGE_HOME="${XSLT_COVERAGE_HOME:-/Users/phil/github/mine/xslt-coverage/}"

[[ -f ./chemistry.config.json.xml ]] || node ./chemistry.config.js

[[ -f ./collection.assembled.xml ]] || xmllint --pretty 1 ../data/chemistry-2e/collection.assembled.xhtml > ./collection.assembled.xml


[[ -d "./coverage" ]] || mkdir "./coverage"

xslt="${XSLT_COVERAGE_HOME}/xslt-coverage.bash"

# ${xslt} ident.xsl ./chemistry.config.json.xml ./coverage/coverage-1.json ./chemistry.config.xml || die "something"
# ${xslt} compile-xslt.xsl ./chemistry.config.xml ./coverage/coverage-2.json ./autogenerated.xsl || die "something"
# ${xslt} transform.xsl ./collection.assembled.xml ./coverage/coverage-3.json ./output-transform.xml || die "something"
# ${xslt} autogenerated.xsl ./collection.assembled.xml ./coverage/coverage-4.json ./output-autogenerated.xml || die "something"


# Numbering figures: 7sec with saxon. 6sec with xsltproc. ?? with parallel saxon
# Numbering paragraphs: 17sec with saxon. 133sec with xsltproc. ?? with parallel saxon
java -jar "${SAXON_HOME}"/saxon9he.jar \
    "-xsl:bake-challenge.xsl" \
    "-s:./collection.assembled.xml" \
    > /dev/null || die 'Failed to convert'

# ${xslt} bake-challenge.xsl ./collection.assembled.xml ./coverage/coverage-5.json ./output-baked-challenge.xml || die "something"

# node "${XSLT_COVERAGE_HOME}/mergeCoverageFiles.js" ./coverage/coverage-1.json ./coverage/coverage-2.json ./coverage/coverage-3.json ./coverage/coverage-4.json > ./coverage/coverage-final.json


echo
echo "Done. Check output-autogenerated.xml to see the result."
echo "Check *.xsl.coverage.xhtml to see an HTML code coverage report for each XSLT file"