docker-compose run --rm fetch-book --with-resources chemistry-2e              
docker-compose run --rm fetch-book --with-resources chemistry-atoms-first-2e  
docker-compose run --rm fetch-book --with-resources anatomy                   
docker-compose run --rm fetch-book --with-resources biology-2e                
docker-compose run --rm fetch-book --with-resources apbiology                 
docker-compose run --rm fetch-book --with-resources concepts-biology          
docker-compose run --rm fetch-book --with-resources microbiology              
docker-compose run --rm fetch-book --with-resources physics                   
docker-compose run --rm fetch-book --with-resources apphysics                 
docker-compose run --rm fetch-book --with-resources u-physics-vol1            
docker-compose run --rm fetch-book --with-resources u-physics-vol2            
docker-compose run --rm fetch-book --with-resources u-physics-vol3            
docker-compose run --rm fetch-book --with-resources pl-u-physics-vol1         
docker-compose run --rm fetch-book --with-resources pl-u-physics-vol2         
docker-compose run --rm fetch-book --with-resources pl-u-physics-vol3         
docker-compose run --rm fetch-book --with-resources hsphysics                 
docker-compose run --rm fetch-book --with-resources entrepreneurship          
docker-compose run --rm fetch-book --with-resources college-success           
docker-compose run --rm fetch-book --with-resources aphistory                 
docker-compose run --rm fetch-book --with-resources psychology-2e             
docker-compose run --rm fetch-book --with-resources prealgebra-2e             
docker-compose run --rm fetch-book --with-resources elementary-algebra-2e     
docker-compose run --rm fetch-book --with-resources intermediate-algebra-2e   
docker-compose run --rm fetch-book --with-resources hs-statistics             
docker-compose run --rm fetch-book --with-resources astronomy                 
docker-compose run --rm fetch-book --with-resources principles-management     
docker-compose run --rm fetch-book --with-resources organizational-behavior   
docker-compose run --rm fetch-book --with-resources accounting-vol-1          
docker-compose run --rm fetch-book --with-resources accounting-vol-2          
docker-compose run --rm fetch-book --with-resources business-ethics           
docker-compose run --rm fetch-book --with-resources business-law              
docker-compose run --rm fetch-book --with-resources intro-business            
docker-compose run --rm fetch-book --with-resources econ-2e                   
docker-compose run --rm fetch-book --with-resources macroecon-2e              
docker-compose run --rm fetch-book --with-resources macroeconap-2e            
docker-compose run --rm fetch-book --with-resources microecon-2e              
docker-compose run --rm fetch-book --with-resources microeconap-2e            
docker-compose run --rm fetch-book --with-resources sociology-2e              
docker-compose run --rm fetch-book --with-resources history                   
docker-compose run --rm fetch-book --with-resources american-government-2e    
docker-compose run --rm fetch-book --with-resources statistics                
docker-compose run --rm fetch-book --with-resources business-statistics       
docker-compose run --rm fetch-book --with-resources calculus-vol1             
docker-compose run --rm fetch-book --with-resources calculus-vol2             
docker-compose run --rm fetch-book --with-resources calculus-vol3             
docker-compose run --rm fetch-book --with-resources college-algebra           
docker-compose run --rm fetch-book --with-resources precalculus               
docker-compose run --rm fetch-book --with-resources algebra-trigonometry      