#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111


bookName=$1
rawFile=$2
bakedFile=$3
debugFlag=$4

sassFile="./recipes/books/${bookName}/book.scss"
cssFile="./recipes/output/${bookName}.css"

# Check command line args

[[ "${bookName}" ]] || die 'Argument Missing. You must specify the name of the book as the 1st argument. For example: physics. The required arguments are: bookName, rawFile, bakedFile'

[[ -f "${rawFile}" ]] || die "Could not find the raw HTML file at ${rawFile}"

[[ "${bakedFile}" ]] || die 'You must specify a baked path'

[[ -f "${sassFile}" ]] || die "Could not find the raw SCSS file at ${sassFile}"


# Remove the baked file if it exists
# [ -e "${bakedFile}" ] && rm ${bakedFile}
# commented out because it could be /dev/stdout

lcovFile="${rawFile}.lcov"

do_progress_quiet "Baking file" \
  cnx-easybake --coverage-file "${lcovFile}" ${debugFlag} "${cssFile}" "${rawFile}" "${bakedFile}"

# Validate the cooked file.
# Commented because snippets do not pass the data-type="metadata" validation
# and adding in all those metadata blocks would be cumbersome and distract
# from the actual use-case which is to show snippets.
# cnx-epub-validate-collated ${bakedFile}
