#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

set -e

# This re-bakes a book on ${HOST} (or all books if using the --all argument)

# Snippet that inspired this script:
#
# To "re-bake” a book is something like:
# - Inject a recipe into the archive in association with the book to be collated.
# `wget https://raw.githubusercontent.com/Connexions/cte/recipes/books/recipes/output/physics.css`
# `/var/cnx/venvs/archive/bin/cnx-archive-inject_resource --resource-filename "recipe.css" --media-type "text/css" /etc/cnx/archive/app.ini 031da8d3-b525-429c-80cf-6c8ed997733a@9.30 physics.css`
# - Invoke the collation via a the python interpreter `import requests; resp = requests.post('http://dev00.cnx.org.cnx.org:6543/contents/031da8d3-b525-429c-80cf-6c8ed997733a/collate-content', headers={'x-api-key': 'b07'}); print(resp)`
# Originally from: https://gist.github.com/pumazi/93f5ed32cb9e094e5a97415ced480a16

arg1=$1
bookVersion=$2

# Pull in the BOOK_CONFIGS
source ./books.txt || exit 1

# Check command line args

if [[ -z "${arg1}" ]]; then
  _say "Valid books are (from ./books.txt):"
  for bookConfig in "${BOOK_CONFIGS[@]}"; do
    read -r bookName recipeName uuid _ <<< "${bookConfig}"
    _say "${bookName}"
  done
  die 'Argument Missing. You must specify the name of the book as the 1st argument or --all for all books (see books.txt). For example: physics'
fi

if [[ "${arg1}" == "--all" ]]; then
  die "--all is not supported because you have to specify the version of the book to bake"
else
  # Filter BOOK_CONFIGS to only contain the book you want to fetch
  for bookConfig in "${BOOK_CONFIGS[@]}"; do
    read -r bookConfigName recipeName uuid hostName _ <<< "${bookConfig}"

    if [[ "${arg1}" = "${bookConfigName}" ]]; then
      BOOK_CONFIGS=("${bookConfigName} ${recipeName} ${uuid} ${hostName}")
      foundConfig=1
      break
    fi
  done

  if [[ ! 1 -eq "${foundConfig}" ]]; then
    _say "Valid books are (from ./books.txt):"
    for bookConfig in "${BOOK_CONFIGS[@]}"; do
      read -r bookName recipeName uuid _ <<< "${bookConfig}"
      _say "${bookName}"
    done
    die "Could not find Book info for book named ${arg1}"
  fi
fi

if [[ -z "${bookVersion}" ]]; then

  # The first entry is always the book info because "--all" is not a valid commandline arg
  read -r bookName recipeName uuid hostName _ <<< "${BOOK_CONFIGS[0]}"

  _say 'ERROR: Argument Missing. You must specify the book version as the 2nd argument for what you want to cook (I know, it is annoying)'
  _say 'The version is the @#.## in the target collection URL'
  die "You can visit http://${hostName}/contents/${uuid} to get the version number"
  exit 1
fi

do_progress_quiet "Compoling CSS files" \
  ./script/compile-books

for bookConfig in "${BOOK_CONFIGS[@]}"; do
  read -r bookName recipeName uuid hostName _ <<< "${bookConfig}"

  cssFile="./recipes/output/${recipeName}.css"

  if [[ -z "${uuid}" ]]; then
    die "Could not find Book UUID for book named ${bookName}"
  fi

  progress "Baking book ${bookName} ${uuid} on ${hostName} ..."

  # shellcheck disable=SC2016
  tempCssFile='${HOME}/temp.css'

  do_progress_quiet "Copying CSS file from local machine to server" \
    scp "${cssFile}" "${USER}@${hostName}:${tempCssFile}"

  buildBookCmd="/var/cnx/venvs/archive/bin/cnx-archive-inject_resource --resource-filename \"recipe.css\" --media-type \"text/css\" /etc/cnx/archive/app.ini \"${uuid}@${bookVersion}\" ${tempCssFile}"
  # shellcheck disable=SC2029
  do_progress_quiet "Injecting the css file into the book as recipe.css" \
    ssh "${USER}@${hostName}" "${buildBookCmd}"

  do_progress_quiet "Re-baking the book (may take up to 12 minutes)" \
    python -c "import requests; resp = requests.post('http://${hostName}:6600/contents/${uuid}@${bookVersion}/baked', headers={'x-api-key': 'b07'}); print(resp)"

  restartVarnishCmd="varnishadm ban req.url '~' ."
  # shellcheck disable=SC2029
  do_progress_quiet "restarting varnish because the HTML files may be cached" \
    ssh "${USER}@${hostName}" "${restartVarnishCmd}"

  _say "Build complete. See the changes by going to http://${hostName}/contents/${uuid}@${bookVersion}"

done
