#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

arg1=$1

styles_root="./styles/books"
# By default, compile all the books (but not the '__book-template')
book_paths="$(ls -d ${styles_root}/*/ | grep --invert-match '__')"

sass_bin="$(npm bin)/sass"
output_dir="./styles/output"

if [ ! "${arg1}" == "" ]; then
  book_paths=("${styles_root}/${arg1}")
fi



for book_path in ${book_paths}; do

  book_name="$(basename ${book_path})"
  sass_file="${styles_root}/${book_name}/${book_name}.scss"
  css_file="${output_dir}/${book_name}.css"

  do_progress "Generating ${css_file}" \
    "${sass_bin}" --source-map "${sass_file}" "${css_file}"
done
