#!/bin/bash

# Run ./script/chop-book {book_name} {chapter_number} in between assemble-book and bake-book
# The script removes all chapters except the one provided. 
# The replacement is done in-place so if a dev wants to change chapters they will need to re-run assemble-book

#delete temp recipe 

book_name=$1
chapter_number=$2
temp_recipe="./recipes/temp-${book_name}.css"
chopped_baked_book="./data/${book_name}/collection.baked.chopped.xhtml"
assembled_book="./data/${book_name}/collection.assembled.xhtml"

touch ${temp_recipe}



echo "nav#toc > ol > li:not(:nth-of-type(${chapter_number})) { move-to: trash } 
[data-type=\"chapter\"]:not(:nth-of-type(${chapter_number})) { move-to: trash } 
body:deferred::after { 
    content: clear(trash);
  }" > ${temp_recipe}

cnx-easybake -d ${temp_recipe} ${assembled_book} ${chopped_baked_book}

#mv ${chomped_baked_book} ${assembled_book}
rm ${temp_recipe}

