#!/bin/bash
cd "$(dirname "$0")/.." || exit 111

./script/setup || exit 111

# Run the tests (which happens to re-generate the CSS files)
./script/test || exit 111

# Verify that the CSS files were regenerated so they never become out-of-sync

hasChanges=$(git diff)

if [[ ! -z "${hasChanges}" ]]; then
  echo "ERROR: Running the tests caused unexpected changes in committed files."
  echo "Were the CSS files regenerated? Be sure to run ./script/test before pushing"
  git diff
  exit 1
fi
