#!/bin/bash

arg1=$1

# Pull in the BOOK_CONFIGS and RECIPE_NAMES
source ./books.txt || exit 1

# Initialize rbenv (if installed)
[[ -n $(which rbenv) ]] && eval "$(rbenv init -)"


if [ ! "${arg1}" == "" ]
then
  RECIPE_NAMES=(${arg1})
fi

# Try running sass locally (using rbenv). If that does not work then try it globally
if [[ $(bundle exec sass --version 2>/dev/null) ]]
then
  sassBin="bundle exec sass"
elif [[ $(sass --version 2>/dev/null) ]]
then
  >&2 echo "INFO: Using system-installed $(sass --version)"
  sassBin="sass"
else
  >&2 echo "ERROR: Could not find sass executable"
  exit 1
fi


for recipeName in "${RECIPE_NAMES[@]}"
do

  sassFile="./recipes/books/${recipeName}/book.scss"
  cssFile="./recipes/output/${recipeName}.css"

  >&2 echo "==> Generating ${cssFile}"

  ${sassBin} ${sassFile} ${cssFile} || exit 1
done
