#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

arg1=$1

# Pull in the BOOK_CONFIGS and RECIPE_NAMES
source ./books.txt || exit 1

if [ ! "${arg1}" == "" ]; then
  RECIPE_NAMES=(${arg1})
fi


sass_bin="$(npm bin)/node-sass"
output_dir="./recipes/output/"

for recipe_name in "${RECIPE_NAMES[@]}"; do

  sass_file="./recipes/books/${recipe_name}/book.scss"
  css_file="${output_dir}/${recipe_name}.css"

  do_progress_quiet "Generating ${css_file}" \
    "${sass_bin}" --source-map true --output-style nested "${sass_file}" "${css_file}"
done

do_progress_quiet "Generating CSS manifest" \
  ./script/build-manifest
