#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111


arg1=$1

# Pull in the BOOK_CONFIGS
source ./books.txt || exit 1

# Check command line args

do_progress_quiet "Preparing styleguide for diffing" \
  ./script/diff-guide-prepare "${arg1}" "baked"


if [[ ! "${arg1}" == "--all" ]]; then
  # Filter BOOK_CONFIGS to only contain the book you want to fetch
  for recipeName in "${RECIPE_NAMES[@]}"; do

    if [[ "${arg1}" = "${recipeName}" ]]; then
      RECIPE_NAMES=("${recipeName}")
      foundConfig=1
      break
    fi
  done

  if [[ ! 1 -eq "${foundConfig}" ]]; then
    _say "Valid books are (from ./books.txt):"
    for recipeName in "${RECIPE_NAMES[@]}"; do
      _say "${recipeName}"
    done
    die "Could not find Book info for recipe named ${arg1}"
  fi
fi

diffFound=0
for recipeName in "${RECIPE_NAMES[@]}"; do

  progress "Checking for differences in '${recipeName}'"

  while IFS= read -r -d '' bakedFile; do # generic for loop

    preparedFile="${bakedFile/-baked/-prepared}"
    if [[ -s "${preparedFile}" ]]; then

      diffCount=$(diff "${preparedFile}" "${bakedFile}" | wc -l)

      if [[ 0 -ne "${diffCount}" ]]; then
        _say "WARNING: There were ${diffCount} differences found. To see all of them run diff ${preparedFile} ${bakedFile}:"
        diffFound=1
      fi

    else
      die "FAILING ${recipeName} because the prepared file '${preparedFile}' was not found. Did you run './script/diff-guide-prepare ${recipeName}' earlier?"
    fi

  done < <(find "./tmp/${recipeName}" -name "*-baked.xhtml" -print0)
done

if [[ ! "${diffFound}" -eq "0" ]]; then
  die "There were differences found so failing"
fi
