#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

arg1=$1

# Pull in the BOOK_CONFIGS
source ./books.txt || exit 1

# Check command line args

if [[ -z "${arg1}" ]]; then
  _say 'This script bakes the book and then compares to the prepared book'
  _say '(done earlier, usually in another branch)'
  _say ''
  _say "Valid books are (from ./books.txt):"
  for bookConfig in "${BOOK_CONFIGS[@]}"; do
    read -r bookName recipeName uuid _ <<< "${bookConfig}"
    _say "${bookName}"
  done

  die 'Argument Missing. You must specify the name of the book as the 1st argument or --all for all books.'
fi


if [[ ! "${arg1}" == "--all" ]]; then
  # Filter BOOK_CONFIGS to only contain the book you want to fetch
  for bookConfig in "${BOOK_CONFIGS[@]}"; do
    read -r bookConfigName recipeName uuid _ <<< "${bookConfig}"

    if [[ "${arg1}" = "${bookConfigName}" ]]; then
      BOOK_CONFIGS=("${bookConfigName} ${recipeName} ${uuid}")
      foundConfig=1
      break
    fi
  done

  if [[ ! 1 -eq "${foundConfig}" ]]; then
    _say "Valid books are (from ./books.txt):"
    for bookConfig in "${BOOK_CONFIGS[@]}"; do
      read -r bookName recipeName uuid _ <<< "${bookConfig}"
      _say "${bookName}"
    done
    die "Could not find Book info for book named ${arg1}"
  fi
fi

for bookConfig in "${BOOK_CONFIGS[@]}"; do
  read -r bookName recipeName uuid _ <<< "${bookConfig}"

  bakedFile="./data/${bookName}-baked.xhtml"
  preparedFile="./data/${bookName}-prepared.xhtml"

  if [[ -s "${preparedFile}" ]]; then

    do_progress_quiet "Baking book" \
      ./script/bake-book "${bookName}" --use-repeatable-ids

    diffCount=$(diff "${preparedFile}" "${bakedFile}" | wc -l)

    if [[ 0 -ne "${diffCount}" ]]; then
      _say "There were ${diffCount} differences found"
      _say "To see all of them run the following:"
      _say "diff ${preparedFile} ${bakedFile}"
      if [[ ! ${DO_ALL} ]]; then
        die "Exiting because differences were found"
      fi
    fi

  else

    _say "SKIPPING ${bookName} because the prepared file was not found."
    _say "Did you run './script/diff-book-prepare ${bookName}' earlier?"
  fi


done
