#!/bin/bash


arg1=$1
bakedOrPreparedSuffix=$2

# Pull in the BOOK_CONFIGS
source ./books.txt || exit 1

# Check command line args

if [[ -z "${arg1}" ]]
then
  >&2 echo 'ERROR: Argument Missing. You must specify the name of the recipe as the 1st argument'
  >&2 echo ' or --all for all recipes.'
  >&2 echo 'This script prepares the guide to compare against.'
  >&2 echo 'Typically this step is done in the master branch'
  >&2 echo 'and then in another branch diff-guide is called to see how the HTML changed.'
  >&2 echo ''
  >&2 echo "Valid recipes are (from ./books.txt):"
  for recipeName in "${RECIPE_NAMES[@]}"
  do
    >&2 echo "${recipeName}"
  done
  exit 1
fi

if [[ -z "${bakedOrPreparedSuffix}" ]]
then
  bakedOrPreparedSuffix="prepared"
fi


if [[ ! "${arg1}" == "--all" ]]
then
  # Filter BOOK_CONFIGS to only contain the book you want to fetch
  for recipeName in "${RECIPE_NAMES[@]}"
  do

    if [[ "${arg1}" = "${recipeName}" ]]
    then
      RECIPE_NAMES=("${recipeName}")
      foundConfig=1
      break
    fi
  done

  if [[ ! 1 -eq "${foundConfig}" ]]
  then
    >&2 echo "ERROR: Could not find Book info for recipe named ${arg1}"
    >&2 echo "Valid books are (from ./books.txt):"
    for recipeName in "${RECIPE_NAMES[@]}"
    do
      >&2 echo "${recipeName}"
    done
    exit 1
  fi
fi

for recipeName in "${RECIPE_NAMES[@]}"
do
  ./script/generate-guide "${recipeName}" "${bakedOrPreparedSuffix}" || exit 1
done
