#!/usr/bin/env bash
cd "$(dirname "$0")/.." || exit 111
source ./books.txt || exit 1

rm ./FEATURES.md

counter=0

for recipe_name in "${RECIPE_NAMES[@]}"; do
  echo -e "\$RECIPE_NAME: \"${recipe_name}\";\\n" | \
    cat  - ./recipes/books/_feature.scss | \
    node ./js/check-feature-enabled/extract-chart.js $counter >> \
    ./FEATURES.md
  counter=$((counter+1))
done
