#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

# SASS does not have an elegant way to find unused variables.
# This crude script uses regular expressions and some variable-name-checking
# to find unused variables.
#
# Valid "Global" variables are those that either:
# - start with "Config_"
# - are all UPPER_CASE (enums)

# Approach:
# 1. Find variable declaration in the form of "$my-var: anyvalue"
# 2. Loop through found variables and find occurrences of each variable in all sass files
# 3. Filter out vars that occurred only once


rootDir="./recipes"

# Counter for the exit status
unusedVarCount=0

reVariableDeclaration1='^$[a-zA-Z0-9_-][^:]*'
reVariableDeclaration2='s/$\([a-zA-Z0-9_-][^:]*\).*/\1/'

progress "Finding variables that are declared but could never possibly be used (conservative)"
vars=$(find "${rootDir}" -type f -name "*.scss" -exec grep --color=never -h "${reVariableDeclaration1}" {} \; | sed "${reVariableDeclaration2}")
for varName in $vars; do
  varCount=$(find "${rootDir}" -type f -name "*.scss" -exec grep --color=never -h "$varName" "{}" \; | wc -l)
  if [[ "${varCount}" -eq 1 ]]; then
    _say "  Unused variable '\$${varName}'"
    ((unusedVarCount+=1))
  fi
done


# Define a helper named begins_with
begins_with() { case $2 in "$1"*) true;; *) false;; esac; }

progress "Finding variables that do not begin with 'Config_' and are not used in the local file"
while IFS= read -r -d '' filePath; do # generic for loop
  vars=$(grep "${reVariableDeclaration1}" "${filePath}" | sed "${reVariableDeclaration2}")
  for varName in $vars; do
    varCount=$(grep -c "\$${varName}" "${filePath}")
    # NOTE: Skip vars that begin with $Config_ or are all $UPPER_CASE (constants)
    if [[ "${varCount}" -eq 1 && "${varName}" != $(echo "${varName}" | tr '[:lower:]' '[:upper:]') ]]; then
      if ! begins_with "Config_" "${varName}"; then
        _say "  ${filePath}: Unused local variable '\$${varName}'"
        ((unusedVarCount+=1))
      fi
    fi
  done
done < <(find "${rootDir}" -type f -name "*.scss" -print0)

exit ${unusedVarCount}
