#!/bin/bash

# Fail when any part of the script fails
set -e

xsl_file="./script/fix-epub-inter-module-links.xsl"

root_dir=$1

if [[ ! ${root_dir} ]]; then
  echo "Specify a path to the unzipped epub as the 1st argument to this script"
  exit 1
fi


for file_name in $(ls ${root_dir}/contents/*.xhtml); do
  xsltproc ${xsl_file} ${file_name} > temp.xhtml
  cp temp.xhtml ${file_name}
done

rm temp.xhtml
