#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

recipeName=$1
bakedOrPreparedSuffix=$2 # Overridden when running ./diff-guide-prepare

sassDir='./recipes/'
styleguideDir="./styleguide/${recipeName}"
sassFile="${sassDir}/books/${recipeName}/book.scss"
cssFile="${styleguideDir}/guide.css"
guideHomepageFile="./guide-homepage.md" # Relative to ${sassDir}/recipes/

tempDir="./tmp/"
tempRecipeDir="${tempDir}/${recipeName}/"
bookDocumentationDir="./recipes/books/${recipeName}"
kssOutputFile="${tempDir}/kss-output.txt"

sassBin="$(npm bin)/node-sass"

# Check command line args

[[ "${recipeName}" ]] || die 'Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'

if [[ -z "${bakedOrPreparedSuffix}" ]]; then
  bakedOrPreparedSuffix="baked"
else
  _say "INFO: Generating -${bakedOrPreparedSuffix}.xhtml files instead of -baked.xhtml files"
fi


[[ -e ${styleguideDir} ]] || mkdir -p ${styleguideDir} || exit 111

do_progress_quiet "Compiling the guide.scss file for ${recipeName}" \
  ${sassBin} --source-map true ${sassFile} ${cssFile}

${sassBin} --source-map true ${sassFile} ${cssFile} || exit 1


progress "Generating the baked example HTML files"

# Create a temporary directory which contains the recipes/mixins/ and recipes/${recipeName} directories.
# This is because we want the styleguide to contain docs of all the common/ elements
# and the book-specific elements, and kss only allows you to point to 1 directory
# to look at all the SASS files.
[[ -d "${tempDir}" ]] || mkdir "${tempDir}" || exit 111

# Keep the tempRecipeDir around because it could have been created by diff-guide-prepare
[[ -d "${tempRecipeDir}" ]] || mkdir "${tempRecipeDir}" || exit 111


# Copy over all the dirs containing the styleguide comments that need to be included

# Pull in the BOOK_CONFIGS
source ./books.txt || exit 111

# Filter BOOK_CONFIGS to only contain the book you want to fetch
for bookConfig in "${BOOK_CONFIGS[@]}"; do
  read -r bookConfigName recipeConfigName uuid hostName basedOns <<< "${bookConfig}"

  if [[ "${recipeName}" = "${recipeConfigName}" ]]; then
    # Actually copy the directories over (like common/,books/physics/)
    IFS=',' read -ra basedOnDirs <<< "$basedOns"
    for basedOnDirName in "${basedOnDirs[@]}"; do
      do_progress_quiet "Including ${sassDir}/${basedOnDirName}" \
        cp -R "${sassDir}/${basedOnDirName}" "${tempRecipeDir}/$(basename ${basedOnDirName})"
    done
    foundConfig=1
    break
  fi
done

[[ 1 -eq "${foundConfig}" ]] || die "Could not find Book info for book named ${recipeName}. check ./books.txt"

cp -R "${bookDocumentationDir}" "${tempRecipeDir}" || exit 111


# Find all the styleguide html files and convert them
for snippetFileName in $(find "${tempRecipeDir}" -name "*.snippet.xml"); do

  snippetBase="$(dirname "${snippetFileName}")/$(basename "${snippetFileName}" .snippet.xml)"
  rawFileName="${snippetBase}.raw.xhtml"
  # This is the filename in the CSS comment
  destFileName="${snippetBase}.xhtml-${bakedOrPreparedSuffix}.html"

  # Convert the snippet (which is HTML + CNXML) into just HTML
  xsltproc ./script/_cnxml-to-xhtml.xsl "${snippetFileName}" > "${rawFileName}" || exit 111

  # commented because xmllint does not like html5 element names like <figure>
  # ./script/bake-file ${recipeName} ${snippetFileName} /dev/stdout | xmllint --html --format - > ${snippetFileName}-baked.xhtml
  # use `source` so we do not have to re-initialize python/node/ruby
  do_progress_quiet "Baking ${rawFileName}" \
    source ./script/bake-file ${recipeName} ${rawFileName} ${rawFileName}-temp1-${bakedOrPreparedSuffix}.xhtml --use-repeatable-ids  || exit 111

  # Construct an HTML file that contains both the raw and baked HTML
  # so it can be separated in the browser
  # (and so Phil does not have to completely rewrite kss becuase it assumes only 1 file for markup)
  echo '<section class="-kss-autogen-guide-markup" data-kss-format="cnxml">' > "${destFileName}" || exit 111
  cat ${snippetFileName} >> "${destFileName}" || exit 111
  echo '</section>' >> "${destFileName}" || exit 111
  echo '<section class="-kss-autogen-guide-markup" data-kss-format="html-raw">' >> "${destFileName}" || exit 111
  cat ${rawFileName} >> "${destFileName}" || exit 111
  echo '</section>' >> "${destFileName}" || exit 111
  echo '<section class="-kss-autogen-guide-markup" data-kss-format="html-baked">' >> "${destFileName}" || exit 111
  cat ${rawFileName}-temp1-${bakedOrPreparedSuffix}.xhtml >> "${destFileName}" || exit 111
  echo '</section>' >> "${destFileName}" || exit 111

  rm ${rawFileName}-temp1-${bakedOrPreparedSuffix}.xhtml || exit 111
done


if [[ "${bakedOrPreparedSuffix}" == "baked" ]]; then

  # The CSS path is relative to the styleguide directory, hence `./guide.css`
  # Exclude parsing the output/*.css files by setting the --mask
  do_progress_quiet "Generating the style guide" \
    $(npm bin)/kss-node --verbose \
    --template ./js/openstax-kss-builder \
    --homepage ${guideHomepageFile} \
    --destination ${styleguideDir} \
    --css ./guide.css \
    --source ${tempRecipeDir} \
    --mask '*.less|*.sass|*.scss|*.styl|*.stylus' > "${kssOutputFile}"

  # HACK: KSS-node does not error if an HTML file is missing. Instead, it prints out a warning.
  # So, check the output of kss to see if any errors were reported.
  missingFiles=$(cat "${kssOutputFile}" | grep 'NOT FOUND!' )
  if [[ -n "${missingFiles}" ]]; then
    die "Some HTML files were missing: ${missingFiles}. Check ${kssOutputFile} for more details"
  fi

  # Generate an HTML report (if genhtml is installed)
  if [[ -n "$(which genhtml)" ]]; then
    do_progress_quiet "Generating HTML coverage report" \
      genhtml --quiet --output ./coverage/ $(find "${tempRecipeDir}" -name "*.lcov")
  fi

  _say "Guide is available at ${styleguideDir}/index.html . You can open it in a browser"

else
  _say "INFO: Skipping actual styleguide generation because the additional arg '${bakedOrPreparedSuffix}' was provided (probably for diff-guide-prepare)"
fi
