#!/bin/sh
set -e

branchNameWithNewStuff=$(git rev-parse --abbrev-ref HEAD)

if [ "${branchNameWithNewStuff}" = "gh-pages" ]
then
  echo "You are running this script in the gh-pages branch. It should be run in another branch (the one with new code changes)"
  exit 1
fi

# Check to make sure there are no uncommitted files
stagedFilesCount=$(git status -s | wc -l)
if [ ${stagedFilesCount} -ne 0 ]
then
  echo "You have uncommitted files. Please commit them first. Aborting."
  git status -s
  exit 1
fi

git checkout gh-pages
git pull # In case gh-pages has updated since you last pulled
git rebase ${branchNameWithNewStuff}

./script/test
git add --all styleguide/
git add --all sassdoc/
git add --all coverage/
git commit -m "Updating guide from ${branchNameWithNewStuff} branch"
git push --force-with-lease origin gh-pages

git checkout ${branchNameWithNewStuff}
