#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

# shellcheck disable=SC2046
shellcheck $(find ./script -not -path '*/\.*' -mindepth 1 -maxdepth 1 -type f) ./books.txt
