#!/bin/bash

env_vars=()

while echo "$1" | grep -q '='
do
  env_vars[${#env_vars[@]}]='-e'
  env_vars[${#env_vars[@]}]="$1"
  shift
done

docker build -t run-image .
docker run --rm -it --name somename run-image /bin/bash   #how to keep open to run bash??
# docker exec "${env_vars[@]}" somename "$@"
#-compose run --rm "${env_vars[@]}" command "$@
