#!/bin/bash
set -e

./script/bootstrap || exit 1

>&2 echo "==> Installing JavaScript Packages"
if [[ $(which yarn) ]]; then
  yarn install || exit 1
else
  >&2 echo "WARNING: Installing JS packages using npm instead of yarn."
  npm install || exit 1
fi


# Only activate the virtualenv if not already in one
if [[ -z "${VIRTUAL_ENV}" ]]
then

  # This is mostly for travis
  if [[ -z "$(which virtualenv)" ]]
  then
    >&2 echo "==> Installing Python virtualenv (pip install virtualenv)"
    pip install virtualenv
  fi

  >&2 echo "==> Setting up a python virtualenv"
  virtualenv ./venv/
  source ./venv/bin/activate
else
  >&2 echo "==> Skipping virtualenv because already in one"
fi

pip install -U pip

if [[ -n "${VIRTUAL_ENV}" ]]
then

  >&2 echo "==> Installing python packages"
  pip install -r ./requirements.txt

else
  echo "ERROR. Not in a virtualenv"
  exit 1
fi


# Clone the rhaptos.cnxmlutils repo in here
if [[ ! -d ./vendor/rhaptos.cnxmlutils/.git/ ]]; then
  >&2 echo "==> Installing ./vendor/rhaptos.cnxmlutils/"
  git clone https://github.com/Connexions/rhaptos.cnxmlutils.git ./vendor/rhaptos.cnxmlutils/
else
  >&2 echo "==> Using existing ./vendor/rhaptos.cnxmlutils/"
fi

>&2 echo "==> Checking out branch in ./vendor/rhaptos.cnxmlutils/ (see https://github.com/Connexions/rhaptos.cnxmlutils/pull/157)"

cd "./vendor/rhaptos.cnxmlutils/"
git checkout rng-fixes
git pull
cd ..
