#!/bin/bash
set -e

./script/bootstrap


# Only activate the virtualenv if not already in one
if [[ -z "${VIRTUAL_ENV}" ]]
then

  # This is mostly for travis
  if [[ -z "$(which virtualenv)" ]]
  then
    >&2 echo "==> Installing Python virtualenv (pip install virtualenv)"
    pip install virtualenv
  fi

  >&2 echo "==> Setting up a python virtualenv"
  virtualenv ./venv/
  source ./venv/bin/activate
else
  >&2 echo "==> Skipping virtualenv because already in one"
fi

pip install -U pip

if [[ -n "${VIRTUAL_ENV}" ]]
then

  >&2 echo "==> Installing python packages"
  pip install -r ./requirements.txt

else
  echo "ERROR. Not in a virtualenv"
  exit 1
fi
