#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

# Verify exportable recipes
try pytest tests

# Make sure the snippets are well-formed XML
do_progress_quiet "Linting and checking XML snippets" \
  ./script/lint-snippets

# Generate the CSS files for books
do_progress_quiet "Compiling CSS files" \
  ./script/compile-books

# Run the linter
do_progress_quiet "Running SASS linter" \
  npm test

do_progress_quiet "Looking for unused variables" \
  ./script/find-unused-vars

# Make sure the docs and guides still generate
do_progress_quiet "Generating sass docs" \
  ./script/generate-docs

# Pull in the BOOK_CONFIGS and BOOK_NAMES
source ./books.txt || exit 1

for recipe_name in "${RECIPE_NAMES[@]}"; do
  do_progress_quiet "Generating styleguide for ${recipe_name}" \
    ./script/generate-guide "${recipe_name}"
done

if [[ ${CI} = 'true' ]]; then
  do_progress_quiet "Cleaning up temporary dir so Travis does not run out of space" \
    rm -rf "./tmp/${recipe_name}/"
fi

# Generate an index.html page for the styleguide
styleguide_dir="./styleguide/"

echo "<html><body><ul>" > "${styleguide_dir}/index.html"
for recipe_name in "${RECIPE_NAMES[@]}"; do
  echo "<li><a href='./${recipe_name}/'>${recipe_name}</a></li>" >> "${styleguide_dir}/index.html"
done
echo "</ul></body></html>" >> "${styleguide_dir}/index.html"


# Generate an HTML report (if genhtml is installed)
if [[ -n "$(which genhtml)" ]]; then
  coverage_files=$(find ./tmp/ -name "*.lcov")
  # shellcheck disable=SC2086
  do_progress_quiet "Generating HTML Coverage report at ./coverage/" \
    genhtml --quiet --output ./coverage/ ${coverage_files}
fi

# Validate the shell scripts
if [[ $(which shellcheck) ]]; then
  do_progress_quiet "Linting shell scripts" \
    ./script/lint-scripts
fi
