#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

# Verify exportable recipes
pytest tests

# Make sure the snippets are well-formed XML
do_progress_quiet "Linting and checking XML snippets" \
  ./script/lint-snippets

# Generate the CSS files for books
do_progress_quiet "Compiling CSS files" \
  ./script/compile-books

# Run the linter
do_progress_quiet "Running SASS linter" \
  npm test

do_progress_quiet "Looking for unused variables" \
  ./script/find-unused-vars

# Make sure the docs and guides still generate
do_progress_quiet "Generating sass docs" \
  ./script/generate-docs

# Pull in the BOOK_CONFIGS and BOOK_NAMES
source ./books.txt || exit 1

for recipeName in "${RECIPE_NAMES[@]}"; do
  do_progress_quiet "Generating styleguide for ${recipeName}" \
    ./script/generate-guide "${recipeName}"
done

# Generate an index.html page for the styleguide
styleguideDir="./styleguide/"

echo "<html><body><ul>" > "${styleguideDir}/index.html"
for recipeName in "${RECIPE_NAMES[@]}"; do
  echo "<li><a href='./${recipeName}/'>${recipeName}</a></li>" >> "${styleguideDir}/index.html"
done
echo "</ul></body></html>" >> "${styleguideDir}/index.html"


# Generate an HTML report (if genhtml is installed)
if [[ -n "$(which genhtml)" ]]; then
  coverage_files=$(find ./tmp/ -name "*.lcov")
  # shellcheck disable=SC2086
  do_progress_quiet "Generating HTML Coverage report at ./coverage/" \
    genhtml --quiet --output ./coverage/ ${coverage_files}
fi

# Validate the shell scripts
if [[ $(which shellcheck) ]]; then
  # shellcheck disable=SC2086
  do_progress_quiet "Linting shell scripts" \
    shellcheck $(find ./script -not -path '*/\.*' -mindepth 1 -maxdepth 1 -type f) ./books.txt
fi
