#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

do_progress_quiet 'Reinstalling python packages' \
  pip install -r requirements.txt

 # Use --force so that the packages are reinstalled
do_progress_quiet "Reinstalling NodeJS package.json" \
  rm ./../node_modules || die "No JS modules installed"
  [[ $(command -v yarn) ]] && yarn install --prefer-offline || \
    [[ $(command -v npm) ]] && npm install
