#!/bin/sh
set -e

script/bootstrap

# Activate the venv if not already in a virtualenv
if [[ -z "${VIRTUAL_ENV}" ]]
then
  source ./venv/bin/activate
fi

if [[ -n "${VIRTUAL_ENV}" ]]
then
  >&2 echo '==> Reinstalling python packages'
  pip install -r requirements.txt

else
  echo "Error. Not in a virtualenv"
  exit 1
fi

>&2 echo "==> Updating sassdoc to the version listed in package.json"
npm install
