#!/bin/bash

for file_name in $(find ./recipes/books/*/styleguide/*.xhtml); do
  echo "${file_name}"

  without_ext="$(dirname "${file_name}")/$(basename "${file_name}" .xhtml)"
  snippet_file="${without_ext}.snippet.xml"
  raw_file="${without_ext}.raw.xml"

  if xsltproc ./script/xsl/_xhtml-to-cnxml.xsl "${file_name}" > "${snippet_file}"; then
    xsltproc ./script/xsl/_cnxml-to-xhtml.xsl "${snippet_file}" > "${raw_file}"
  else
    exit 1
  fi

  # rm ${snippet_file}
  rm "${raw_file}"
done

for file_name in $(find ./recipes/mixins/styleguide/*.xhtml); do
  echo "${file_name}"

  without_ext="$(dirname "${file_name}")/$(basename "${file_name}" .xhtml)"
  snippet_file="${without_ext}.snippet.xml"
  raw_file="${without_ext}.raw.xml"

  if xsltproc ./script/xsl/_xhtml-to-cnxml.xsl "${file_name}" > "${snippet_file}"; then
    xsltproc ./script/xsl/_cnxml-to-xhtml.xsl "${snippet_file}" > "${raw_file}"
  else
    exit 1
  fi

  # rm ${snippet_file}
  rm "${raw_file}"
done
