#!/bin/bash
set -e


bookName=$1
bookConfigFile="./books.txt"

if [ -z "${bookName}" ]
then
  >&2 echo "This utility script converts a book name (like microecon)"
  >&2 echo "to the ruleset name the should be used to generate the book"
  >&2 echo "(like economics) by looking up the value in ./books.txt"
  >&2 echo "but you need to enter a valid book name as the argument to"
  >&2 echo "this file"
  exit 1
fi

if [ ! -f "${bookConfigFile}" ]
then
  >&2 echo "ERROR: Could not find the file named ${bookConfigFile}"
  exit 1
fi


# load up all the vars stored in ${bookConfigFile}
source ${bookConfigFile}

# Loop through all the configs and find the one that matches the book we want
for bookConfig in "${BOOK_CONFIGS[@]}"
do
  read -r bookConfigName rulesetName uuid <<< "${bookConfig}"

  if [[ "${bookName}" = "${bookConfigName}" ]]
  then
    echo ${rulesetName} ${uuid}
    exit 0
  fi

done

>&2 echo "ERROR: could not find a ruleset_name for the book named ${bookName}"
>&2 echo "Please check the ${bookConfigFile} file and make sure the entry exits"
exit 1
