#!/bin/bash
set -e

bookName=$1
RAW_PATH=$2
BAKED_PATH=$3
DEBUG_FLAG=$4

sassFile="./books/rulesets/${bookName}/book.scss"
cssFile="./books/rulesets/output/${bookName}.css"

# Check command line args

if [ -z "${bookName}" ]
then
  echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
  echo 'The required arguments are: bookName, RAW_PATH, BAKED_PATH'
  exit 1
fi

if [ ! -f "${RAW_PATH}" ]
then
  echo "ERROR: Could not find the raw HTML file at ${RAW_PATH}"
  exit 1
fi

if [ -z "${BAKED_PATH}" ]
then
  echo 'ERROR: You must specify a baked path'
  exit 1
fi

if [ ! -f "${sassFile}" ]
then
  echo "ERROR: Could not find the raw SCSS file at ${sassFile}"
  exit 1
fi


# Remove the baked file if it exists
# [ -e "${BAKED_PATH}" ] && rm ${BAKED_PATH}
# commented out because it could be /dev/stdout

# Activate the venv if not running Travis or already in a virtualenv
if [[ ! "${CI}" = "true" && -z "${VIRTUAL_ENV}" ]]
then
  . ./venv/bin/activate
fi

cnx-easybake ${DEBUG_FLAG} ${cssFile} ${RAW_PATH} ${BAKED_PATH}
# Validate the cooked file.
# Commented because snippets do not pass the data-type="metadata" validation
# and adding in all those metadata blocks would be cumbersome and distract
# from the actual use-case which is to show snippets.
# cnx-epub-validate-collated ${BAKED_PATH}
