#!/bin/sh
set -e

BOOK_NAME=$1
RAW_PATH=$2
COOKED_PATH=$3
DEBUG_FLAG=$4

SASS_PATH="./books/rulesets/${BOOK_NAME}/book.scss"
CSS_PATH="./books/rulesets/output/${BOOK_NAME}.css"

# Check command line args

if [ -z "${BOOK_NAME}" ]
then
  echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
  echo 'The required arguments are: BOOK_NAME, RAW_PATH, COOKED_PATH'
  exit 1
fi

if [ ! -f "${RAW_PATH}" ]
then
  echo "ERROR: Could not find the raw HTML file at ${RAW_PATH}"
  exit 1
fi

if [ -z "${COOKED_PATH}" ]
then
  echo 'ERROR: You must specify a cooked path'
  exit 1
fi

if [ ! -f "${SASS_PATH}" ]
then
  echo "ERROR: Could not find the raw SCSS file at ${SASS_PATH}"
  exit 1
fi


# Remove the cooked file if it exists
# [ -e "${COOKED_PATH}" ] && rm ${COOKED_PATH}
# commented out because it could be /dev/stdout

# Activate the venv if not running Travis or already in a virtualenv
if [[ ! "${CI}" = "true" && -z "${VIRTUAL_ENV}" ]]
then
  . ./venv/bin/activate
fi

cnx-easybake ${DEBUG_FLAG} ${CSS_PATH} ${RAW_PATH} ${COOKED_PATH}
# Validate the cooked file.
# Commented because snippets do not pass the data-type="metadata" validation
# and adding in all those metadata blocks would be cumbersome and distract
# from the actual use-case which is to show snippets.
# cnx-epub-validate-collated ${BAKED_PATH}
