#!/bin/bash

# Resolve all dependencies that the application requires to run.
# From https://github.com/github/scripts-to-rule-them-all/blob/master/script/bootstrap

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  >&2 echo "==> Updating Homebrew…"
  brew update

  brew bundle check >/dev/null 2>&1  || {
    >&2 echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

# Note: Skip rbenv for Travis because it already has ruby
if [ ! "${CI}" = "true" ] && [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  >&2 echo "==> Installing Ruby…"
  rbenv install --skip-existing
fi

>&2 echo "Using ruby via rbenv:"
rbenv version

which bundle >/dev/null 2>&1  || {
  >&2 echo "==> Installing Ruby Bundler gem…"
  rbenv version
  gem install bundler
  rbenv rehash
}

if [ -f "Gemfile" ]; then
  >&2 echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production
  }
fi


>&2 echo "==> Installing Node package dependencies"
>&2 echo "Using node: $(node --version)"
>&2 echo "Using npm: $(npm --version)"
npm install || exit 1
