#!/bin/bash
set -e

# Run the tests (which happens to re-generate the CSS files)
./scripts/test

# Verify that the CSS files were regenerated so they never become out-of-sync

hasChanges=$(git diff)

if [[ ! -z "${hasChanges}" ]]
then
  echo "ERROR: Running the tests caused unexpected changes in committed files."
  echo "Were the CSS files regenerated? Be sure to run ./scripts/test before pushing"
  git diff
  exit 1
fi

# report lcov data to coveralls
npm run-script coveralls
