#!/bin/bash

# Pull in the BOOK_CONFIGS and RULESET_NAMES
source ./books.txt || exit 1

# Initialize rbenv (if installed)
[[ -n $(which rbenv) ]] && eval "$(rbenv init -)"

for rulesetName in "${RULESET_NAMES[@]}"
do

  sassFile="./rulesets/books/${rulesetName}/book.scss"
  cssFile="./rulesets/output/${rulesetName}.css"

  >&2 echo "==> Generating ${cssFile}"

  bundle exec sass ${sassFile} ${cssFile} || exit 1
done
