#!/bin/bash

# Pull in the BOOK_CONFIGS and RULESET_NAMES
source ./books.txt || exit 1

for rulesetName in "${RULESET_NAMES[@]}"
do

  sassFile="./books/rulesets/${rulesetName}/book.scss"
  cssFile="./books/rulesets/output/${rulesetName}.css"

  >&2 echo "==> Generating ${cssFile}"

  bundle exec sass ${sassFile} ${cssFile} || exit 1
done
