#!/bin/sh
set -e


bookName=$1
debugFlag=$2

bakedFile="./data/${bookName}-baked.html"
PREPARED_PATH="./data/${bookName}-prepared.html"

# Check command line args

if [ -z "${bookName}" ]
then
  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
  >&2 echo 'This script bakes the book and then compares to the prepared book'
  >&2 echo '(done earlier, usually in another branch)'
  exit 1
fi

if [ ! -f "${PREPARED_PATH}" ]
then
  >&2 echo 'ERROR: This book was not prepared beforehand.'
  >&2 echo 'Run diff-book-prepare before running this script'
  >&2 echo 'so there is something to compare against'
  exit 1
fi

./scripts/bake-book ${bookName}

diff ${PREPARED_PATH} ${bakedFile}
