#!/bin/sh
set -e


bookName=$1
DEBUG_FLAG=$2

BAKED_PATH="./data/${bookName}-baked.html"
PREPARED_PATH="./data/${bookName}-prepared.html"

# Check command line args

if [ -z "${bookName}" ]
then
  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
  >&2 echo 'This script prepares the book to compare against.'
  >&2 echo 'Typically this step is done in the master branch'
  >&2 echo 'and then in another branch diff-book is called to see how the HTML changed.'
  exit 1
fi

./scripts/bake-book ${bookName}

mv ${BAKED_PATH} ${PREPARED_PATH}
