#!/bin/sh
set -e

# . ./bin/activate
# deactivate

HOST='cte-cnx-dev.cnx.org'

BOOK_NAME=$1

RULESET_NAME_AND_UUID=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${BOOK_NAME}))
BOOK_UUID_AND_VER=${RULESET_NAME_AND_UUID[1]}

RAW_PATH="./data/${BOOK_NAME}-raw.html"

# Check command line args

if [ -z "${BOOK_NAME}" ]
then
  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
  exit 1
fi

if [ -z "${BOOK_UUID_AND_VER}" ]
then
  >&2 echo 'ERROR: Argument Missing. You must specify the UUID of the book to download as the 2nd argument. For example: 30189442-6998-4686-ac05-ed152b91b9de@19.2'
  exit 1
fi


>&2 echo "Step 1/2: Generating an EPUB from the database and converting to a single HTML file (may take a minute)"

TEMP_EPUB_PATH="~/temp.intenral.epub"
TEMP_HTML_PATH="~/temp.html"

RM_TEMP_EPUB_CMD="[ -e ${TEMP_EPUB_PATH} ] && rm ${TEMP_EPUB_PATH}"
RM_TEMP_HTML_CMD="[ -e ${TEMP_HTML_PATH} ] && rm ${TEMP_HTML_PATH}"
GENERATE_EPUB_CMD="/var/cnx/venvs/publishing/bin/cnx-archive-export_epub /etc/cnx/publishing/app.ini ${BOOK_UUID_AND_VER} ${TEMP_EPUB_PATH}"
GENERATE_HTML_CMD="/var/cnx/venvs/publishing/bin/cnx-epub-single_html ${TEMP_EPUB_PATH} > ${TEMP_HTML_PATH}"

CMD="${RM_TEMP_EPUB_CMD}; ${RM_TEMP_HTML_CMD}; ${GENERATE_EPUB_CMD} && ${GENERATE_HTML_CMD}"

ssh ${USER}@${HOST} ${CMD}

>&2 echo "Step 2/2: Copying HTML file from server to local machine"
scp ${USER}@${HOST}:${TEMP_HTML_PATH} ${RAW_PATH}

>&2 echo "Fetch is done. File is available at ${RAW_PATH}"
