#!/bin/sh
set -e

# . ./bin/activate
# deactivate

HOST='cte-cnx-dev.cnx.org'

BOOK_NAME=$1
BOOK_UUID_AND_VER=$2

RAW_PATH="./data/${BOOK_NAME}-raw.html"

# Check command line args

if [ -z "${BOOK_NAME}" ]
then
  echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument. For example: physics'
  exit 1
fi

if [ -z "${BOOK_UUID_AND_VER}" ]
then
  echo 'ERROR: Argument Missing. You must specify the UUID of the book to download as the 2nd argument. For example: 30189442-6998-4686-ac05-ed152b91b9de@19.2'
  exit 1
fi


echo "Step 1/2: Generating an EPUB from the database and converting to a single HTML file (may take a minute)"

COMMAND="[ -e ~/temp.internal.epub ] && rm ~/temp.internal.epub; /var/cnx/venvs/publishing/bin/cnx-archive-export_epub /etc/cnx/publishing/app.ini ${BOOK_UUID_AND_VER} ~/temp.internal.epub && /var/cnx/venvs/publishing/bin/cnx-epub-single_html ~/temp.internal.epub > ~/temp.html"

ssh ${HOST} ${COMMAND}

echo "Step 2/2: Copying HTML file from server to local machine"
scp ${HOST}:~/temp.html ${RAW_PATH}

echo "Fetch is done. File is available at ${RAW_PATH}"
