#!/usr/bin/env node

'use strict'

var fs = require('fs')
var path = require('path')
var jsdom = require('jsdom')
var argv = require('yargs')
  .demand(['b'])
  .alias('b', 'book')
  .alias('t', 'type')
  .describe('b', 'Book name (from books.txt)')
  .describe('t', 'Type (raw or cooked)')
  .default('t', 'cooked')
  .argv

var htmlPath = path.join(__dirname, `../data/${argv.b}-${argv.t}.html`)
console.log(`Checking ${htmlPath}`)

var html = fs.readFileSync(htmlPath, 'utf-8')

function generateSelector(el) {
  if (el.hasAttribute('id')) {
    return `${el.tagName.toLowerCase()}#${el.getAttribute('id')}`
  } else if (el.className) {
    return `${generateSelector(el.parentNode)} > ${el.tagName.toLowerCase()}.${el.className.split(' ').join('.')}` // Replace spaces with dots
  } else {
    return `${generateSelector(el.parentNode)} > ${el.tagName.toLowerCase()}`
  }
}

jsdom.env(html, [], function(err, window) {
  var errorCount = 0 // Used for exit status
  var links = window.document.querySelectorAll('a[href]')
  for (var link of links) {
    var href = link.getAttribute('href')
    if (/^#/.test(href)) { // check if the href begins with a # (an internal link)
      var target = window.document.getElementById(href.replace('#', ''))
      if (!target) {
        errorCount += 1
        console.error(`Broken internal link: a[href]="${href}" selector="${generateSelector(link)}" link-text="${link.textContent}"`)
      }
    } else {
      // TODO: verify external links
    }
  }
  process.exit(errorCount)

});
