#!/bin/sh
set -e

echo "Step 1/1: Generating docs"
./node_modules/.bin/sassdoc --verbose --dest=./sassdoc/ ./books/

echo "Docs are available at ./sassdoc/index.html . You can open them in a browser"
