#!/bin/bash

>&2 echo "==> Generating SASSdocs"
$(npm bin)/sassdoc --verbose --dest=./sassdoc/ ./rulesets/ || exit 1

>&2 echo "Docs are available at ./sassdoc/index.html . You can open them in a browser"
