#!/bin/sh
set -e

>&2 echo "==> Generating SASSdocs"
$(npm bin)/sassdoc --verbose --dest=./sassdoc/ ./rulesets/

>&2 echo "Docs are available at ./sassdoc/index.html . You can open them in a browser"
