#!/bin/sh
set -e


ARG1=$1
DEBUG_FLAG1=$2 # could be --debug or --verbose (or both)
DEBUG_FLAG2=$3

# Check command line args

if [ -z "${ARG1}" ]
then
  >&2 echo 'ERROR: Argument Missing. You must specify the name of the book as the 1st argument or --all for all books. For example: physics'
  exit 1
fi

if [ "${ARG1}" == "--all" ]
then
  source ./books.txt
else
  BOOK_LIST="${ARG1}"
fi

for bookName in ${BOOK_LIST}
do

  RAW_PATH="./data/${bookName}-raw.html"
  LCOV_PATH="./data/${bookName}.lcov"

  if [ -f "${RAW_PATH}" ]
  then

    RULESET_NAME_AND_UUID=($(./scripts/_convert-bookname-to-ruleset-name-and-uuid ${bookName}))
    RULESET_NAME=${RULESET_NAME_AND_UUID[0]}

    cssFile="./books/rulesets/output/${RULESET_NAME}.css"

    if [ ! -f "${cssFile}" ]
    then
      >&2 echo "ERROR: CSS File missing at ${cssFile}"
      exit 1
    fi

    # Print out the message first because css-coverage will set
    # a non-zero exit status if there are unused selectors
    # and the `set -e` at the top of this script will exit at that point

    if [ "${ARG1}" == "--all" ]
    then
      >&2 echo "Generating coverage for ${bookName} in ${LCOV_PATH}"
    else
      >&2 echo "Coverage is being generated. To see an HTML version, run the following:"
      >&2 echo "genhtml ${LCOV_PATH} --output-directory ./coverage"
      >&2 echo "Note: to run this you may need to install genhtml. In OSX it is 'brew install lcov'"
    fi

    ./node_modules/.bin/css-coverage --css ${cssFile} --html ${RAW_PATH} --lcov ${LCOV_PATH} ${DEBUG_FLAG1} ${DEBUG_FLAG2}

  else
    if [ "${ARG1}" == "--all" ]
    then
      >&2 echo "WARNING: Skipping ${bookName} because HTML File is missing at ${RAW_PATH}"
    else
      >&2 echo "ERROR: HTML File missing at ${RAW_PATH}"
      exit 1
    fi
  fi

done

if [ "${ARG1}" == "--all" ]
then
  >&2 echo "Generated coverage for ${BOOK_LIST}. To see an HTML version, run the following:"
  >&2 echo "genhtml ./data/*.lcov --output-directory ./coverage"
  >&2 echo "Note: to run this you may need to install genhtml. In OSX it is 'brew install lcov'"
fi
