#!/bin/bash
set -e

./scripts/bootstrap


if [[ ! "${CI}" = "true" ]] # Skip when running Travis
then
  # Only activate the virtualenv if not already in one
  if [[ -z "${VIRTUAL_ENV}" ]]
  then
    echo "==> Setting up a python virtualenv"
    virtualenv ./venv/
    . ./venv/bin/activate
  else
    echo "==> Skipping virtualenv because already in one"
  fi
fi


if [[ ( "${CI}" = "true" ) || ( -n "${VIRTUAL_ENV}" ) ]]
then

  echo "==> Installing python packages"

  pip install --quiet git+https://github.com/Connexions/cssselect2.git
  pip install --quiet git+https://github.com/Connexions/cnx-easybake.git
  pip install --quiet git+https://github.com/Connexions/cnx-epub.git

else
  echo "ERROR. Not in a virtualenv"
  exit 1
fi

echo "==> Installing sassdoc (depends on NodeJS)"
npm install
