#!/bin/bash

# Generate the CSS files for books
./scripts/compile-books || exit 1

# Run the linter
npm test || exit 1
./scripts/find-unused-vars || exit 1

# Make sure the docs and guides still generate
./scripts/generate-docs || exit 1

# Pull in the BOOK_CONFIGS and BOOK_NAMES
source ./books.txt || exit 1

for rulesetName in "${RULESET_NAMES[@]}"
do
  ./scripts/generate-guide "${rulesetName}" || exit 1
done

# Generate an index.html page for the styleguide
styleguideDir="./styleguide/"

echo "<html><body><ul>" > "${styleguideDir}/index.html"
for rulesetName in "${RULESET_NAMES[@]}"
do
  echo "<li><a href='./${rulesetName}/'>${rulesetName}</a></li>" >> "${styleguideDir}/index.html"
done
echo "</ul></body></html>" >> "${styleguideDir}/index.html"


# Generate an HTML report (if genhtml is installed)
if [[ -n "$(which genhtml)" ]]
then
  >&2 echo "==> Generating HTML Coverage report at ./coverage/"
  genhtml --quiet --output ./coverage/ $(find ./tmp/ -name "*.lcov") || exit 1
fi
