#!/bin/bash
set -e

# Run the linter
npm test

# Generate the CSS files for books
./scripts/compile-books

# Make sure the docs and guides still generate
./scripts/generate-docs

# Find all the rulesets that need to be generated
for bookName in $(cd ./books/rulesets/ && ls -d -- */ )
do
  bookName=$(basename "${bookName}") # Strip the trailing /
  if [[ ! "${bookName}" = 'output' && ! "${bookName}" = 'common' ]]
  then
    >&2 echo "==> Generating Guide for ${bookName}"
    ./scripts/generate-guide "${bookName}" || exit 1
  fi
done
