#!/bin/sh
set -e

scripts/bootstrap

# Activate the venv if not running Travis or already in a virtualenv
if [[ ! "${CI}" = "true" && -z "${VIRTUAL_ENV}" ]]
then
  . ./venv/bin/activate
fi

if [[ ( "${CI}" = "true" ) || ( -n "${VIRTUAL_ENV}" ) ]]
then
  echo '==> Uninstalling python packages'
  pip uninstall --yes -r requirements.txt

  echo '==> Reinstalling python packages'
  pip install -r requirements.txt

else
  echo "Error. Not in a virtualenv"
  exit 1
fi

echo "==> Updating sassdoc to the version listed in package.json"
npm install
