#!/bin/sh
set -e

scripts/bootstrap

# Activate the venv if not running Travis or already in a virtualenv
if [[ ! "${CI}" = "true" && -z "${VIRTUAL_ENV}" ]]
then
  . ./venv/bin/activate
fi

if [[ ( "${CI}" = "true" ) || ( -n "${VIRTUAL_ENV}" ) ]]
then
  echo '==> Uninstalling python packages'

  pip uninstall --quiet --yes requests # Used for rebaking a book
  pip uninstall --quiet --yes cssselect2
  pip uninstall --quiet --yes rhaptos.cnxmlutils
  pip uninstall --quiet --yes cnx-archive
  pip uninstall --quiet --yes cnx-easybake
  pip uninstall --quiet --yes cnx-epub


  echo '==> Reinstalling python packages'

  pip install requests # Used for rebaking a book
  pip install --quiet git+https://github.com/Connexions/cssselect2.git
  pip install --quiet git+https://github.com/Connexions/rhaptos.cnxmlutils.git
  pip install --quiet git+https://github.com/Connexions/cnx-archive.git
  pip install --quiet git+https://github.com/Connexions/cnx-easybake.git
  pip install --quiet git+https://github.com/Connexions/cnx-epub.git

else
  echo "Error. Not in a virtualenv"
  exit 1
fi

echo "==> Updating sassdoc to the version listed in package.json"
npm install
