#!/bin/sh
set -e

echo 'Step 1/3: Updating SASS'

gem update --quiet sass

echo 'Step 2/3: Uninstalling python packages'

virtualenv .
. ./bin/activate

pip uninstall --quiet --yes cssselect2
pip uninstall --quiet --yes rhaptos.cnxmlutils
pip uninstall --quiet --yes cnx-archive
pip uninstall --quiet --yes cnx-easybake
pip uninstall --quiet --yes cnx-epub


echo 'Step 3/3: Reinstalling python packages'

pip install --quiet git+https://github.com/Connexions/cssselect2.git
pip install --quiet git+https://github.com/Connexions/rhaptos.cnxmlutils.git
pip install --quiet git+https://github.com/Connexions/cnx-archive.git
pip install --quiet git+https://github.com/Connexions/cnx-easybake.git
pip install --quiet git+https://github.com/Connexions/cnx-epub.git

deactivate
